title: madStacks
description: A slowly expanding collection of random posts and CTF resources
permalink: /blog/:year/:month/:day/:title
author: madStacks
theme: jekyll-theme-time-machine
show_downloads: false